name: Windows Build & Test

on:
  push:
    branches:
      - 'master'
      - 'fix/*'
      - 'feat/*'
  pull_request:
    branches: [ master ]
    types:
      - created
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GIT_TERMINAL_PROMPT: 0
  working-directory: C:\Dreamweave

jobs:
  Windows:
    strategy:
      matrix:
        build_type: [ Release ]
    runs-on: windows-2022

    steps:
      - name: Clone
        shell: bash
        working-directory: C:\
        run: |
          git clone https://github.com/DreamWeave-MP/Dreamweave.git
          cd Dreamweave
          git checkout ${{ github.head_ref }}

      - name: Prime ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ matrix.BUILD_TYPE }}-ccache
          max-size: 2250M
          verbose: 2

      - name: Cache Windows Deps
        id: cache-WinDeps
        uses: actions/cache@v3
        with:
          path: |
            C:/Dreamweave/deps/ICU-70_1/
            C:/Dreamweave/deps/LuaJIT/
            C:/Dreamweave/deps/LZ4_1.9.2/
            C:/Dreamweave/deps/openal-soft-1.23.0-bin/
            C:/Dreamweave/deps/SDL2-2.24.0/
            C:/Dreamweave/deps/zlib-1.2.11-msvc2017-win64/
            C:/Dreamweave/extern/raknet
            C:/Dreamweave/MSVC2022_64_Ninja/deps/
            C:/Dreamweave/MSVC2022_64_Ninja/*.ninja
          key: ${{ runner.os }}-deps

      - name: Install Building Dependencies
        if: steps.cache-WinDeps.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ env.working-directory }}
        run: |
          curl -o CrabNet.7z -L https://github.com/DreamWeave-MP/CrabNet/releases/download/Stable-CI/CrabNet-${{ runner.os }}-${{ matrix.BUILD_TYPE }}.7z
          7z x -y CrabNet.7z -oextern/raknet
          CI/before_script.msvc.sh -C -V -N -k -p Win64 -v 2022

      - name: Configure
        if: steps.cache-WinDeps.outputs.cache-hit == 'true'
        shell: bash
        working-directory: ${{ env.working-directory }}
        run: |
          CI/before_script.msvc.sh -C -V -N -k -p Win64 -v 2022 -d -e

      - name: Build
        shell: bash
        working-directory: ${{ env.working-directory }}
        run: |
          cd MSVC2022_64_Ninja
          source activate_msvc.sh
          ninja -f build-${{ matrix.BUILD_TYPE }}.ninja


      - name: Package
        shell: bash
        working-directory: ${{ env.working-directory }}
        run: CI/make_package.msvc.sh ${{ matrix.BUILD_TYPE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.working-directory }}/dreamweave-build
          name: dreamweave_windows-${{ matrix.BUILD_TYPE }}
